version: "3.7"
services:
  devshell:
    environment:
        # This expects that your host machine has something like :
        #    export HOST_IP=`ifconfig en0 | awk '/ *inet /{print $2}'`
        # setup.
      - HOST_IP=${HOST_IP}
    build: .
    expose:
      - "8080"
    ports:
        - "8080:8080"
    volumes:
      - /Users/vng/dev:/app/src
      - .:/app/dev
    stdin_open: true
    tty: true
